### PR TITLE
Token authentication python v2

### PR DESCRIPTION
**Pull request by bartlomiejwereszczynski**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@bartlomiejwereszczynski can we chat on the client-libraries channel please as I don't want to review all these new PRs when existing PRs have my feedback and allow me to review the changes.  I am not sure I understand why you issued new PRs for every PR that existed instead of simply amending the PRs.  I will wait to hear from you before reviewing anything further if that is OK

**Comment by mattheworiordan** [comment]
@bartlomiejwereszczynski these PRs are all closed now?  Out of interest, what is your plan?

**Comment by bartlomiejwereszczynski** [comment]
@mattheworiordan I've Pushed contents of code sample branches to their respective branches in ably/tutorials like you've asked.  

Next thing is to prepare code samples and tutorial update for "Publish & Subscribe Tutorial".

**Comment by mattheworiordan** [comment]
@bartlomiejwereszczynski ah nice, I hadn't seen that, thanks @bartlomiejwereszczynski.  Can I assume all feedback was incorporated then or do I need to review?

**Comment by bartlomiejwereszczynski** [comment]
All feedback was incorporated in those branches, i've also updated branch with python tutorials: https://github.com/ably/docs/pull/167 branch after the merge of tutorials with PHP code so it's ready to be merged as well.

**Pull request closed without merging**
