### PR TITLE
Webhooks and Ruby on Rails demo calling the Chuck Norris Jokes API

### PR DESCRIPTION
**Pull request by mattheworiordan**
As we don't have any Ruby on Rails examples, I thought I'd build a WebHooks demo that shows how to use Auth with Rails, receive WebHooks and publish messages back to Ably using the REST library.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
FYI, this is now published to https://queue-wolfram-alpha-tuto-pr-37.herokuapp.com/

**Comment by paddybyers** [comment]
Is this still worth reviewing?

**Comment by mattheworiordan** [comment]
See https://github.com/ably/tutorials/pull/36. @tomczoink ca you do the same please?

**Review by paddybyers — APPROVED** [review]
FWIW LGTM

**Pull request closed without merging**
