### PR TITLE
History, Swift samples

### PR DESCRIPTION
**Pull request by ShelinHime**

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Pushed up to https://github.com/ably/tutorials/commits/history-swift.  Can you confirm that this PR has all issues addressed please?

**Comment by ShelinHime** [comment]
Yes, I've created new commits with separate step for xcodeproject setup and Ably installation. I've also added some guard statements so that user will know at all times what is happening in the app and what's the API connection status. Everything is done in UI and is presented in 
a view(received messages, channel history etc.) or as alerts(api key not changed, successful/failed connection, possible error ocurrence etc.).
The same goes to the publish and subscribe PR.

**Comment by mattheworiordan** [comment]
> Yes, I've created new commits with separate step for xcodeproject setup and Ably installation
> Great, where are those new commits?

**Comment by ShelinHime** [comment]
What do you mean? My comment was regarding you asking if I addressed the all the issues in the previous PR. One was that I should make 2 separate commits for project setup and installing Ably, and that's what I did in this PR.

**Comment by mattheworiordan** [comment]
Oh I misunderstood.  Thanks for clarifying.

**Pull request closed without merging**
