### PR TITLE
Presence ruby update tutorial

### PR DESCRIPTION
**Pull request by marklewin**
Remove individual steps and just show solution code (part of the work required for [EDU-827](https://ably.atlassian.net/browse/EDU-827)

### CODE REVIEW

**Comment by fliptopbox** [comment]
@marklewin i have added a `.tool-versions` file bc my default version of ruby is 3.0.0 (laterst) and this code is not compatible.

**Review by fliptopbox — CHANGES_REQUESTED** [review]
Please restore the README and update the logo old assets and URLs

**Comment by marklewin** [comment]
> @marklewin i have added a `.tool-versions` file bc my default version of ruby is 3.0.0 (laterst) and this code is not compatible.

Many thanks

**Review by fliptopbox — APPROVED** [review]

**Review by fliptopbox — CHANGES_REQUESTED** [review]
please replace ably.io URLs and old logo in README

**Review by fliptopbox — APPROVED** [review]

**Pull request merged**
