### PR TITLE
AMQP Queue Neutrino Profanity filter example wth Node.js

### PR DESCRIPTION
**Pull request by mattheworiordan**
@paddybyers @SimonWoolf another simple queue demo using a public free API

### CODE REVIEW

**Comment by mattheworiordan** [comment]
FYI, running at https://queue-wolfram-alpha-tuto-pr-35.herokuapp.com/

**Comment by paddybyers** [comment]
Is this still worth reviewing?

**Comment by mattheworiordan** [comment]
See https://github.com/ably/tutorials/pull/36. @tomczoink can you do the same?

**Review by paddybyers — APPROVED** [review]
LGTM

**Pull request closed without merging**
