### PR TITLE
Queue STOMP neutrino profanity nodejs

### PR DESCRIPTION
**Pull request by mattheworiordan**
A variation on https://github.com/ably/tutorials/pull/35 which uses STOMP.

Good thing I built this demo as I discovered that to subscribe via STOMP you need the `/amq/queue/` prefix for the queue name, and additionally [our STOMP routing needs](https://github.com/ably/infrastructure/commit/d80133c55ec32ee19d4ccb82008bd8851c9d6379) to work :)

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Running at https://queue-wolfram-alpha-tuto-pr-36.herokuapp.com/

**Comment by paddybyers** [comment]
Is this still worth reviewing?

**Comment by mattheworiordan** [comment]
@paddybyers if you have a mo, yes.  @tomczoink can you just make sure this is merged in once you've reviewed as well?

**Review by tomczoink — APPROVED** [review]

**Review by paddybyers — APPROVED** [review]
LGTM

**Pull request closed without merging**
